In [1]:
import os
from pathlib import Path
from aaai_experiments import *

In [26]:
df_name = 'pr-1-11-1244-A59_m55_l4_noise.csv' 
data_path = 'C:\\Users\\User\\Jupyter Projects\\Datasets'
subfolder = 'pr'
model_path = 'C:\\Users\\User\\Jupyter Projects\\Datasets\\pr\\pr-1-11-1244-A59.txt'
model_output_path = r'C:\Users\User\Jupyter Projects\ConLESHeuristic\model'

n_train_traces = 5
n_test_traces = 20
window_overlap = 0
window_lengths_lst = [20, None]
n_final_markings_lst = [1]
min_len = 80
max_len = None
use_heuristics = True
read_model_from_file = True
return_model = True
print_dataset_stats = True
return_test_df = True

In [27]:
res, model, alignments, test_df = compare_window_based_baselines(
    df_name=df_name,
    n_train_traces=n_train_traces,
    n_test_traces=n_test_traces,
    window_overlap=window_overlap,
    window_lengths_lst=window_lengths_lst,
    n_final_markings_lst=n_final_markings_lst,
    min_len=min_len,
    max_len=max_len,
    use_heuristics=use_heuristics,
    read_model_from_file=read_model_from_file,
    model_path=model_path,
    return_model=return_model,
    data_path=data_path,
    subfolder=subfolder,
    print_dataset_stats=print_dataset_stats,
    return_test_df=return_test_df,
    portion=portion,
    nonsync_density_tolerance=nonsync_density_tolerance
)

Training Dataset Statistics:
Number of traces: 5
Number of unique activities: 67
Number of unique trace variants: 5

Trace Length Statistics:
Average length: 103.60
Min length: 92
Max length: 114

Test Dataset Statistics:
Number of traces: 20
Number of unique activities: 68
Number of unique trace variants: 20

Trace Length Statistics:
Average length: 104.15
Min length: 80
Max length: 128

Starting to compute mandatory transitions...
Mandatory transitions computed in 1.0984 seconds
Starting to compute alive transitions...
Alive transitions computed in 0.0964 seconds
Evaluating variant: n_markings=1, window_len=20
Computing trace 20/20
Evaluating variant: n_markings=1, window_len=None
Computing trace 20/20

In [7]:
visualize_petri_net(model, output_path=model_output_path)

Visualization saved to: C:\Users\User\Jupyter Projects\ConLESHeuristic\model

In [30]:
res

,case_id,window_20_cost,window_20_time,full_window_cost,full_window_time,cost_increase_percentage,alignment_length
0,1257,12.0,0.13,12.0,2.71,0.00,120
1,1295,14.0,0.07,12.0,2.83,16.67,115
2,1357,12.0,0.09,12.0,2.16,0.00,93
3,1406,12.0,0.10,12.0,2.99,0.00,111
4,1416,8.0,0.06,8.0,0.78,0.00,102
5,1526,12.0,0.15,12.0,3.14,0.00,114
6,1625,12.0,0.08,12.0,2.70,0.00,127
7,1649,12.0,0.08,12.0,3.31,0.00,130
8,182,8.0,0.15,8.0,1.61,0.00,105
9,1955,8.0,0.05,8.0,0.86,0.00,104
10,1998,12.0,0.19,12.0,2.87,0.00,125
11,232,12.0,0.07,8.0,0.78,50.00,102
12,299,12.0,0.10,12.0,3.15,0.00,132
13,437,12.0,0.13,12.0,2.78,0.00,134
14,791,10.0,0.07,8.0,1.27,25.00,85
15,83,8.0,0.09,8.0,0.96,0.00,88
16,853,8.0,0.07,8.0,1.08,0.00,87
17,946,14.0,0.17,12.0,2.68,16.67,106
18,989,8.0,0.05,8.0,1.49,0.00,84
19,998,12.0,0.09,12.0,3.57,0.00,128

In [31]:
res

,case_id,window_20_cost,window_20_time,full_window_cost,full_window_time,cost_increase_percentage,alignment_length
0,1257,12.0,0.13,12.0,2.71,0.00,120
1,1295,14.0,0.07,12.0,2.83,16.67,115
2,1357,12.0,0.09,12.0,2.16,0.00,93
3,1406,12.0,0.10,12.0,2.99,0.00,111
4,1416,8.0,0.06,8.0,0.78,0.00,102
5,1526,12.0,0.15,12.0,3.14,0.00,114
6,1625,12.0,0.08,12.0,2.70,0.00,127
7,1649,12.0,0.08,12.0,3.31,0.00,130
8,182,8.0,0.15,8.0,1.61,0.00,105
9,1955,8.0,0.05,8.0,0.86,0.00,104
10,1998,12.0,0.19,12.0,2.87,0.00,125
11,232,12.0,0.07,8.0,0.78,50.00,102
12,299,12.0,0.10,12.0,3.15,0.00,132
13,437,12.0,0.13,12.0,2.78,0.00,134
14,791,10.0,0.07,8.0,1.27,25.00,85
15,83,8.0,0.09,8.0,0.96,0.00,88
16,853,8.0,0.07,8.0,1.08,0.00,87
17,946,14.0,0.17,12.0,2.68,16.67,106
18,989,8.0,0.05,8.0,1.49,0.00,84
19,998,12.0,0.09,12.0,3.57,0.00,128

In [32]:
with pd.option_context('display.max_rows', None):
    display(dict_to_dataframe(alignments, 'window_20', case_id_filter='232'))  # (trace, model)

# dict_to_dataframe(alignments, 'window_15', case_id_filter='989')

,case_id,cost,time,nodes_opened,steps,window_number,transition_names,transition_weights
1246,232,12.0,0.07,632,1,1,"(sync_0_ts=0, sync_0_ts=0)",0.0
1247,232,12.0,0.07,632,2,1,"(sync_1_ts=1, sync_1_ts=1)",0.0
1248,232,12.0,0.07,632,3,1,"(sync_44_ts=2, sync_44_ts=2)",0.0
1249,232,12.0,0.07,632,4,1,"(sync_45_ts=3, sync_45_ts=3)",0.0
1250,232,12.0,0.07,632,5,1,"(sync_63_ts=4, sync_63_ts=4)",0.0
1251,232,12.0,0.07,632,6,1,"(sync_64_ts=5, sync_64_ts=5)",0.0
1252,232,12.0,0.07,632,7,1,"(sync_65_ts=6, sync_65_ts=6)",0.0
1253,232,12.0,0.07,632,8,1,"(sync_66_ts=7, sync_66_ts=7)",0.0
1254,232,12.0,0.07,632,9,1,"(sync_50_ts=8, sync_50_ts=8)",0.0
1255,232,12.0,0.07,632,10,1,"(sync_59_ts=9, sync_59_ts=9)",0.0
1256,232,12.0,0.07,632,11,1,"(sync_60_ts=10, sync_60_ts=10)",0.0
1257,232,12.0,0.07,632,12,1,"(sync_61_ts=11, sync_61_ts=11)",0.0
1258,232,12.0,0.07,632,13,1,"(sync_62_ts=12, sync_62_ts=12)",0.0
1259,232,12.0,0.07,632,14,1,"(sync_45_ts=13, sync_45_ts=13)",0.0
1260,232,12.0,0.07,632,15,1,"(sync_46_ts=14, sync_46_ts=14)",0.0
1261,232,12.0,0.07,632,16,1,"(sync_47_ts=15, sync_47_ts=15)",0.0
1262,232,12.0,0.07,632,17,1,"(sync_48_ts=16, sync_48_ts=16)",0.0
1263,232,12.0,0.07,632,18,1,"(sync_49_ts=17, sync_49_ts=17)",0.0
1264,232,12.0,0.07,632,19,1,"(sync_50_ts=18, sync_50_ts=18)",0.0
1265,232,12.0,0.07,632,20,1,"(sync_59_ts=19, sync_59_ts=19)",0.0
1266,232,12.0,0.07,632,1,2,"(sync_60_ts=0, sync_60_ts=0)",0.0
1267,232,12.0,0.07,632,2,2,"(sync_61_ts=1, sync_61_ts=1)",0.0
1268,232,12.0,0.07,632,3,2,"(sync_62_ts=2, sync_62_ts=2)",0.0
1269,232,12.0,0.07,632,4,2,"(sync_45_ts=3, sync_45_ts=3)",0.0
1270,232,12.0,0.07,632,5,2,"(sync_52_ts=4, sync_52_ts=4)",0.0
1271,232,12.0,0.07,632,6,2,"(sync_53_ts=5, sync_53_ts=5)",0.0
1272,232,12.0,0.07,632,7,2,"(sync_54_ts=6, sync_54_ts=6)",0.0
1273,232,12.0,0.07,632,8,2,"(sync_55_ts=7, sync_55_ts=7)",0.0
1274,232,12.0,0.07,632,9,2,"(sync_56_ts=8, sync_56_ts=8)",0.0
1275,232,12.0,0.07,632,10,2,"(sync_53_ts=9, sync_53_ts=9)",0.0
1276,232,12.0,0.07,632,11,2,"(sync_54_ts=10, sync_54_ts=10)",0.0
1277,232,12.0,0.07,632,12,2,"(sync_55_ts=11, sync_55_ts=11)",0.0
1278,232,12.0,0.07,632,13,2,"(sync_58_ts=12, sync_58_ts=12)",0.0
1279,232,12.0,0.07,632,14,2,"(sync_50_ts=13, sync_50_ts=13)",0.0
1280,232,12.0,0.07,632,15,2,"(sync_51_ts=14, sync_51_ts=14)",0.0
1281,232,12.0,0.07,632,16,2,"(sync_17_ts=15, sync_17_ts=15)",0.0
1282,232,12.0,0.07,632,17,2,"(sync_18_ts=16, sync_18_ts=16)",0.0
1283,232,12.0,0.07,632,18,2,"(20_ts=17, >>)",1
1284,232,12.0,0.07,632,19,2,"(24_ts=18, >>)",1
1285,232,12.0,0.07,632,20,2,"(sync_19_ts=19, sync_19_ts=19)",0.0
1286,232,12.0,0.07,632,1,3,"(sync_21_ts=0, sync_21_ts=0)",0.0
1287,232,12.0,0.07,632,2,3,"(sync_22_ts=1, sync_22_ts=1)",0.0
1288,232,12.0,0.07,632,3,3,"(sync_27_ts=2, sync_27_ts=2)",0.0
1289,232,12.0,0.07,632,4,3,"(sync_19_ts=3, sync_19_ts=3)",0.0
1290,232,12.0,0.07,632,5,3,"(>>, 20)",1
1291,232,12.0,0.07,632,6,3,"(sync_21_ts=4, sync_21_ts=4)",0.0
1292,232,12.0,0.07,632,7,3,"(sync_27_ts=5, sync_27_ts=5)",0.0
1293,232,12.0,0.07,632,8,3,"(sync_19_ts=6, sync_19_ts=6)",0.0
1294,232,12.0,0.07,632,9,3,"(sync_25_ts=7, sync_25_ts=7)",0.0
1295,232,12.0,0.07,632,10,3,"(sync_21_ts=8, sync_21_ts=8)",0.0
1296,232,12.0,0.07,632,11,3,"(sync_23_ts=9, sync_23_ts=9)",0.0
1297,232,12.0,0.07,632,12,3,"(>>, 24)",1
1298,232,12.0,0.07,632,13,3,"(sync_26_ts=10, sync_26_ts=10)",0.0
1299,232,12.0,0.07,632,14,3,"(sync_1_ts=11, sync_1_ts=11)",0.0
1300,232,12.0,0.07,632,15,3,"(sync_2_ts=12, sync_2_ts=12)",0.0
1301,232,12.0,0.07,632,16,3,"(sync_4_ts=13, sync_4_ts=13)",0.0
1302,232,12.0,0.07,632,17,3,"(sync_3_ts=14, sync_3_ts=14)",0.0
1303,232,12.0,0.07,632,18,3,"(sync_6_ts=15, sync_6_ts=15)",0.0
1304,232,12.0,0.07,632,19,3,"(sync_8_ts=16, sync_8_ts=16)",0.0
1305,232,12.0,0.07,632,20,3,"(sync_11_ts=17, sync_11_ts=17)",0.0
1306,232,12.0,0.07,632,21,3,"(sync_15_ts=18, sync_15_ts=18)",0.0
1307,232,12.0,0.07,632,22,3,"(sync_12_ts=19, sync_12_ts=19)",0.0
1308,232,12.0,0.07,632,1,4,"(sync_9_ts=0, sync_9_ts=0)",0.0
1309,232,12.0,0.07,632,2,4,"(sync_10_ts=1, sync_10_ts=1)",0.0
1310,232,12.0,0.07,632,3,4,"(sync_5_ts=2, sync_5_ts=2)",0.0
1311,232,12.0,0.07,632,4,4,"(sync_7_ts=3, sync_7_ts=3)",0.0
1312,232,12.0,0.07,632,5,4,"(sync_14_ts=4, sync_14_ts=4)",0.0
1313,232,12.0,0.07,632,6,4,"(sync_16_ts=5, sync_16_ts=5)",0.0
1314,232,12.0,0.07,632,7,4,"(sync_17_ts=6, sync_17_ts=6)",0.0
1315,232,12.0,0.07,632,8,4,"(sync_18_ts=7, sync_18_ts=7)",0.0
1316,232,12.0,0.07,632,9,4,"(20_ts=8, >>)",1
1317,232,12.0,0.07,632,10,4,"(24_ts=9, >>)",1
1318,232,12.0,0.07,632,11,4,"(sync_19_ts=10, sync_19_ts=10)",0.0
1319,232,12.0,0.07,632,12,4,"(sync_22_ts=11, sync_22_ts=11)",0.0
1320,232,12.0,0.07,632,13,4,"(sync_21_ts=12, sync_21_ts=12)",0.0
1321,232,12.0,0.07,632,14,4,"(sync_25_ts=13, sync_25_ts=13)",0.0
1322,232,12.0,0.07,632,15,4,"(sync_27_ts=14, sync_27_ts=14)",0.0
1323,232,12.0,0.07,632,16,4,"(sync_19_ts=15, sync_19_ts=15)",0.0
1324,232,12.0,0.07,632,17,4,"(sync_21_ts=16, sync_21_ts=16)",0.0
1325,232,12.0,0.07,632,18,4,"(sync_23_ts=17, sync_23_ts=17)",0.0
1326,232,12.0,0.07,632,19,4,"(26_ts=18, >>)",1
1327,232,12.0,0.07,632,20,4,"(1_ts=19, >>)",1
1328,232,12.0,0.07,632,1,5,"(>>, 20)",1
1329,232,12.0,0.07,632,2,5,"(>>, 24)",1
1330,232,12.0,0.07,632,3,5,"(>>, 26)",1
1331,232,12.0,0.07,632,4,5,"(>>, 1)",1
1332,232,12.0,0.07,632,5,5,"(sync_2_ts=0, sync_2_ts=0)",0.0
1333,232,12.0,0.07,632,6,5,"(sync_8_ts=1, sync_8_ts=1)",0.0
1334,232,12.0,0.07,632,7,5,"(sync_10_ts=2, sync_10_ts=2)",0.0
1335,232,12.0,0.07,632,8,5,"(sync_12_ts=3, sync_12_ts=3)",0.0
1336,232,12.0,0.07,632,9,5,"(sync_4_ts=4, sync_4_ts=4)",0.0
1337,232,12.0,0.07,632,10,5,"(sync_9_ts=5, sync_9_ts=5)",0.0
1338,232,12.0,0.07,632,11,5,"(sync_14_ts=6, sync_14_ts=6)",0.0
1339,232,12.0,0.07,632,12,5,"(sync_5_ts=7, sync_5_ts=7)",0.0
1340,232,12.0,0.07,632,13,5,"(sync_3_ts=8, sync_3_ts=8)",0.0
1341,232,12.0,0.07,632,14,5,"(sync_11_ts=9, sync_11_ts=9)",0.0
1342,232,12.0,0.07,632,15,5,"(sync_15_ts=10, sync_15_ts=10)",0.0
1343,232,12.0,0.07,632,16,5,"(sync_6_ts=11, sync_6_ts=11)",0.0
1344,232,12.0,0.07,632,17,5,"(sync_7_ts=12, sync_7_ts=12)",0.0
1345,232,12.0,0.07,632,18,5,"(sync_16_ts=13, sync_16_ts=13)",0.0
1346,232,12.0,0.07,632,19,5,"(sync_17_ts=14, sync_17_ts=14)",0.0
1347,232,12.0,0.07,632,20,5,"(sync_43_ts=15, sync_43_ts=15)",0.0

In [33]:
with pd.option_context('display.max_rows', None):
    display(dict_to_dataframe(alignments, 'window_None', case_id_filter='232'))

,case_id,cost,time,nodes_opened,steps,window_number,transition_names,transition_weights
1245,232,8.0,0.78,5206,1,1,"(sync_0_ts=0, sync_0_ts=0)",0.0
1246,232,8.0,0.78,5206,2,1,"(sync_1_ts=1, sync_1_ts=1)",0.0
1247,232,8.0,0.78,5206,3,1,"(sync_44_ts=2, sync_44_ts=2)",0.0
1248,232,8.0,0.78,5206,4,1,"(sync_45_ts=3, sync_45_ts=3)",0.0
1249,232,8.0,0.78,5206,5,1,"(sync_63_ts=4, sync_63_ts=4)",0.0
1250,232,8.0,0.78,5206,6,1,"(sync_64_ts=5, sync_64_ts=5)",0.0
1251,232,8.0,0.78,5206,7,1,"(sync_65_ts=6, sync_65_ts=6)",0.0
1252,232,8.0,0.78,5206,8,1,"(sync_66_ts=7, sync_66_ts=7)",0.0
1253,232,8.0,0.78,5206,9,1,"(sync_50_ts=8, sync_50_ts=8)",0.0
1254,232,8.0,0.78,5206,10,1,"(sync_59_ts=9, sync_59_ts=9)",0.0
1255,232,8.0,0.78,5206,11,1,"(sync_60_ts=10, sync_60_ts=10)",0.0
1256,232,8.0,0.78,5206,12,1,"(sync_61_ts=11, sync_61_ts=11)",0.0
1257,232,8.0,0.78,5206,13,1,"(sync_62_ts=12, sync_62_ts=12)",0.0
1258,232,8.0,0.78,5206,14,1,"(sync_45_ts=13, sync_45_ts=13)",0.0
1259,232,8.0,0.78,5206,15,1,"(sync_46_ts=14, sync_46_ts=14)",0.0
1260,232,8.0,0.78,5206,16,1,"(sync_47_ts=15, sync_47_ts=15)",0.0
1261,232,8.0,0.78,5206,17,1,"(sync_48_ts=16, sync_48_ts=16)",0.0
1262,232,8.0,0.78,5206,18,1,"(sync_49_ts=17, sync_49_ts=17)",0.0
1263,232,8.0,0.78,5206,19,1,"(sync_50_ts=18, sync_50_ts=18)",0.0
1264,232,8.0,0.78,5206,20,1,"(sync_59_ts=19, sync_59_ts=19)",0.0
1265,232,8.0,0.78,5206,21,1,"(sync_60_ts=20, sync_60_ts=20)",0.0
1266,232,8.0,0.78,5206,22,1,"(sync_61_ts=21, sync_61_ts=21)",0.0
1267,232,8.0,0.78,5206,23,1,"(sync_62_ts=22, sync_62_ts=22)",0.0
1268,232,8.0,0.78,5206,24,1,"(sync_45_ts=23, sync_45_ts=23)",0.0
1269,232,8.0,0.78,5206,25,1,"(sync_52_ts=24, sync_52_ts=24)",0.0
1270,232,8.0,0.78,5206,26,1,"(sync_53_ts=25, sync_53_ts=25)",0.0
1271,232,8.0,0.78,5206,27,1,"(sync_54_ts=26, sync_54_ts=26)",0.0
1272,232,8.0,0.78,5206,28,1,"(sync_55_ts=27, sync_55_ts=27)",0.0
1273,232,8.0,0.78,5206,29,1,"(sync_56_ts=28, sync_56_ts=28)",0.0
1274,232,8.0,0.78,5206,30,1,"(sync_53_ts=29, sync_53_ts=29)",0.0
1275,232,8.0,0.78,5206,31,1,"(sync_54_ts=30, sync_54_ts=30)",0.0
1276,232,8.0,0.78,5206,32,1,"(sync_55_ts=31, sync_55_ts=31)",0.0
1277,232,8.0,0.78,5206,33,1,"(sync_58_ts=32, sync_58_ts=32)",0.0
1278,232,8.0,0.78,5206,34,1,"(sync_50_ts=33, sync_50_ts=33)",0.0
1279,232,8.0,0.78,5206,35,1,"(sync_51_ts=34, sync_51_ts=34)",0.0
1280,232,8.0,0.78,5206,36,1,"(sync_17_ts=35, sync_17_ts=35)",0.0
1281,232,8.0,0.78,5206,37,1,"(sync_18_ts=36, sync_18_ts=36)",0.0
1282,232,8.0,0.78,5206,38,1,"(20_ts=37, >>)",1
1283,232,8.0,0.78,5206,39,1,"(24_ts=38, >>)",1
1284,232,8.0,0.78,5206,40,1,"(sync_19_ts=39, sync_19_ts=39)",0.0
1285,232,8.0,0.78,5206,41,1,"(sync_21_ts=40, sync_21_ts=40)",0.0
1286,232,8.0,0.78,5206,42,1,"(sync_22_ts=41, sync_22_ts=41)",0.0
1287,232,8.0,0.78,5206,43,1,"(sync_27_ts=42, sync_27_ts=42)",0.0
1288,232,8.0,0.78,5206,44,1,"(sync_19_ts=43, sync_19_ts=43)",0.0
1289,232,8.0,0.78,5206,45,1,"(sync_21_ts=44, sync_21_ts=44)",0.0
1290,232,8.0,0.78,5206,46,1,"(sync_27_ts=45, sync_27_ts=45)",0.0
1291,232,8.0,0.78,5206,47,1,"(sync_19_ts=46, sync_19_ts=46)",0.0
1292,232,8.0,0.78,5206,48,1,"(sync_25_ts=47, sync_25_ts=47)",0.0
1293,232,8.0,0.78,5206,49,1,"(sync_21_ts=48, sync_21_ts=48)",0.0
1294,232,8.0,0.78,5206,50,1,"(sync_23_ts=49, sync_23_ts=49)",0.0
1295,232,8.0,0.78,5206,51,1,"(>>, 20)",1
1296,232,8.0,0.78,5206,52,1,"(>>, 24)",1
1297,232,8.0,0.78,5206,53,1,"(sync_26_ts=50, sync_26_ts=50)",0.0
1298,232,8.0,0.78,5206,54,1,"(sync_1_ts=51, sync_1_ts=51)",0.0
1299,232,8.0,0.78,5206,55,1,"(sync_2_ts=52, sync_2_ts=52)",0.0
1300,232,8.0,0.78,5206,56,1,"(sync_4_ts=53, sync_4_ts=53)",0.0
1301,232,8.0,0.78,5206,57,1,"(sync_3_ts=54, sync_3_ts=54)",0.0
1302,232,8.0,0.78,5206,58,1,"(sync_6_ts=55, sync_6_ts=55)",0.0
1303,232,8.0,0.78,5206,59,1,"(sync_8_ts=56, sync_8_ts=56)",0.0
1304,232,8.0,0.78,5206,60,1,"(sync_11_ts=57, sync_11_ts=57)",0.0
1305,232,8.0,0.78,5206,61,1,"(sync_15_ts=58, sync_15_ts=58)",0.0
1306,232,8.0,0.78,5206,62,1,"(sync_12_ts=59, sync_12_ts=59)",0.0
1307,232,8.0,0.78,5206,63,1,"(sync_9_ts=60, sync_9_ts=60)",0.0
1308,232,8.0,0.78,5206,64,1,"(sync_10_ts=61, sync_10_ts=61)",0.0
1309,232,8.0,0.78,5206,65,1,"(sync_5_ts=62, sync_5_ts=62)",0.0
1310,232,8.0,0.78,5206,66,1,"(sync_7_ts=63, sync_7_ts=63)",0.0
1311,232,8.0,0.78,5206,67,1,"(sync_14_ts=64, sync_14_ts=64)",0.0
1312,232,8.0,0.78,5206,68,1,"(sync_16_ts=65, sync_16_ts=65)",0.0
1313,232,8.0,0.78,5206,69,1,"(sync_17_ts=66, sync_17_ts=66)",0.0
1314,232,8.0,0.78,5206,70,1,"(sync_18_ts=67, sync_18_ts=67)",0.0
1315,232,8.0,0.78,5206,71,1,"(>>, 22)",1
1316,232,8.0,0.78,5206,72,1,"(sync_20_ts=68, sync_20_ts=68)",0.0
1317,232,8.0,0.78,5206,73,1,"(>>, 25)",1
1318,232,8.0,0.78,5206,74,1,"(sync_24_ts=69, sync_24_ts=69)",0.0
1319,232,8.0,0.78,5206,75,1,"(sync_19_ts=70, sync_19_ts=70)",0.0
1320,232,8.0,0.78,5206,76,1,"(22_ts=71, >>)",1
1321,232,8.0,0.78,5206,77,1,"(sync_21_ts=72, sync_21_ts=72)",0.0
1322,232,8.0,0.78,5206,78,1,"(25_ts=73, >>)",1
1323,232,8.0,0.78,5206,79,1,"(sync_27_ts=74, sync_27_ts=74)",0.0
1324,232,8.0,0.78,5206,80,1,"(sync_19_ts=75, sync_19_ts=75)",0.0
1325,232,8.0,0.78,5206,81,1,"(sync_21_ts=76, sync_21_ts=76)",0.0
1326,232,8.0,0.78,5206,82,1,"(sync_23_ts=77, sync_23_ts=77)",0.0
1327,232,8.0,0.78,5206,83,1,"(sync_26_ts=78, sync_26_ts=78)",0.0
1328,232,8.0,0.78,5206,84,1,"(sync_1_ts=79, sync_1_ts=79)",0.0
1329,232,8.0,0.78,5206,85,1,"(sync_2_ts=80, sync_2_ts=80)",0.0
1330,232,8.0,0.78,5206,86,1,"(sync_8_ts=81, sync_8_ts=81)",0.0
1331,232,8.0,0.78,5206,87,1,"(sync_10_ts=82, sync_10_ts=82)",0.0
1332,232,8.0,0.78,5206,88,1,"(sync_12_ts=83, sync_12_ts=83)",0.0
1333,232,8.0,0.78,5206,89,1,"(sync_4_ts=84, sync_4_ts=84)",0.0
1334,232,8.0,0.78,5206,90,1,"(sync_9_ts=85, sync_9_ts=85)",0.0
1335,232,8.0,0.78,5206,91,1,"(sync_14_ts=86, sync_14_ts=86)",0.0
1336,232,8.0,0.78,5206,92,1,"(sync_5_ts=87, sync_5_ts=87)",0.0
1337,232,8.0,0.78,5206,93,1,"(sync_3_ts=88, sync_3_ts=88)",0.0
1338,232,8.0,0.78,5206,94,1,"(sync_11_ts=89, sync_11_ts=89)",0.0
1339,232,8.0,0.78,5206,95,1,"(sync_15_ts=90, sync_15_ts=90)",0.0
1340,232,8.0,0.78,5206,96,1,"(sync_6_ts=91, sync_6_ts=91)",0.0
1341,232,8.0,0.78,5206,97,1,"(sync_7_ts=92, sync_7_ts=92)",0.0
1342,232,8.0,0.78,5206,98,1,"(sync_16_ts=93, sync_16_ts=93)",0.0
1343,232,8.0,0.78,5206,99,1,"(sync_17_ts=94, sync_17_ts=94)",0.0
1344,232,8.0,0.78,5206,100,1,"(sync_43_ts=95, sync_43_ts=95)",0.0

In [23]:
with pd.option_context('display.max_rows', None):
    display(test_df[test_df['case:concept:name'] == '989'])

       case:concept:name concept:name  probs
103860               989            0  [1.0]
103861               989            1  [1.0]
103862               989           28  [1.0]
103863               989           31  [1.0]
103864               989           34  [1.0]
103865               989           29  [1.0]
103866               989           36  [1.0]
103867               989           33  [1.0]
103868               989           32  [1.0]
103869               989           35  [1.0]
103870               989           38  [1.0]
103871               989           30  [1.0]
103872               989           37  [1.0]
103873               989           39  [1.0]
103874               989           34  [1.0]
103875               989           38  [1.0]
103876               989           39  [1.0]
103877               989           34  [1.0]
103878               989           38  [1.0]
103879               989           39  [1.0]
103880               989           34  [1.0]
103881               989           38  [1.0]
103882               989           39  [1.0]
103883               989           40  [1.0]
103884               989           34  [1.0]
103885               989           38  [1.0]
103886               989           39  [1.0]
103887               989           34  [1.0]
103888               989           38  [1.0]
103889               989           39  [1.0]
103890               989           34  [1.0]
103891               989           38  [1.0]
103892               989           41  [1.0]
103893               989           42  [1.0]
103894               989           17  [1.0]
103895               989           18  [1.0]
103896               989           19  [1.0]
103897               989           20  [1.0]
103898               989           21  [1.0]
103899               989           23  [1.0]
103900               989           24  [1.0]
103901               989           22  [1.0]
103902               989           25  [1.0]
103903               989           26  [1.0]
103904               989            1  [1.0]
103905               989           44  [1.0]
103906               989           45  [1.0]
103907               989           63  [1.0]
103908               989           64  [1.0]
103909               989           65  [1.0]
103910               989           66  [1.0]
103911               989           50  [1.0]
103912               989           51  [1.0]
103913               989           17  [1.0]
103914               989           18  [1.0]
103915               989           19  [1.0]
103916               989           20  [1.0]
103917               989           21  [1.0]
103918               989           23  [1.0]
103919               989           22  [1.0]
103920               989           24  [1.0]
103921               989           25  [1.0]
103922               989           26  [1.0]
103923               989            1  [1.0]
103924               989           28  [1.0]
103925               989           29  [1.0]
103926               989           30  [1.0]
103927               989           33  [1.0]
103928               989           34  [1.0]
103929               989           38  [1.0]
103930               989           41  [1.0]
103931               989           31  [1.0]
103932               989           32  [1.0]
103933               989           36  [1.0]
103934               989           35  [1.0]
103935               989           37  [1.0]
103936               989           40  [1.0]
103937               989           42  [1.0]
103938               989           17  [1.0]
103939               989           43  [1.0]

In [11]:
with pd.option_context('display.max_rows', None):
    display(dict_to_dataframe(alignments, 'window_15', case_id_filter='1955'))  # (trace, model)

,case_id,cost,time,nodes_opened,steps,window_number,transition_names,transition_weights
1018,1955,12.0,0.18,401,1,1,"(sync_0_ts=0, sync_0_ts=0)",0.0
1019,1955,12.0,0.18,401,2,1,"(sync_1_ts=1, sync_1_ts=1)",0.0
1020,1955,12.0,0.18,401,3,1,"(sync_44_ts=2, sync_44_ts=2)",0.0
1021,1955,12.0,0.18,401,4,1,"(sync_45_ts=3, sync_45_ts=3)",0.0
1022,1955,12.0,0.18,401,5,1,"(sync_52_ts=4, sync_52_ts=4)",0.0
1023,1955,12.0,0.18,401,6,1,"(sync_53_ts=5, sync_53_ts=5)",0.0
1024,1955,12.0,0.18,401,7,1,"(sync_54_ts=6, sync_54_ts=6)",0.0
1025,1955,12.0,0.18,401,8,1,"(sync_55_ts=7, sync_55_ts=7)",0.0
1026,1955,12.0,0.18,401,9,1,"(sync_58_ts=8, sync_58_ts=8)",0.0
1027,1955,12.0,0.18,401,10,1,"(sync_50_ts=9, sync_50_ts=9)",0.0
1028,1955,12.0,0.18,401,11,1,"(sync_59_ts=10, sync_59_ts=10)",0.0
1029,1955,12.0,0.18,401,12,1,"(sync_60_ts=11, sync_60_ts=11)",0.0
1030,1955,12.0,0.18,401,13,1,"(sync_61_ts=12, sync_61_ts=12)",0.0
1031,1955,12.0,0.18,401,14,1,"(sync_62_ts=13, sync_62_ts=13)",0.0
1032,1955,12.0,0.18,401,15,1,"(sync_45_ts=14, sync_45_ts=14)",0.0
1033,1955,12.0,0.18,401,1,2,"(sync_52_ts=0, sync_52_ts=0)",0.0
1034,1955,12.0,0.18,401,2,2,"(sync_53_ts=1, sync_53_ts=1)",0.0
1035,1955,12.0,0.18,401,3,2,"(sync_57_ts=2, sync_57_ts=2)",0.0
1036,1955,12.0,0.18,401,4,2,"(sync_55_ts=3, sync_55_ts=3)",0.0
1037,1955,12.0,0.18,401,5,2,"(sync_56_ts=4, sync_56_ts=4)",0.0
1038,1955,12.0,0.18,401,6,2,"(sync_53_ts=5, sync_53_ts=5)",0.0
1039,1955,12.0,0.18,401,7,2,"(sync_57_ts=6, sync_57_ts=6)",0.0
1040,1955,12.0,0.18,401,8,2,"(sync_55_ts=7, sync_55_ts=7)",0.0
1041,1955,12.0,0.18,401,9,2,"(sync_58_ts=8, sync_58_ts=8)",0.0
1042,1955,12.0,0.18,401,10,2,"(sync_50_ts=9, sync_50_ts=9)",0.0
1043,1955,12.0,0.18,401,11,2,"(sync_59_ts=10, sync_59_ts=10)",0.0
1044,1955,12.0,0.18,401,12,2,"(sync_60_ts=11, sync_60_ts=11)",0.0
1045,1955,12.0,0.18,401,13,2,"(sync_61_ts=12, sync_61_ts=12)",0.0
1046,1955,12.0,0.18,401,14,2,"(sync_62_ts=13, sync_62_ts=13)",0.0
1047,1955,12.0,0.18,401,15,2,"(sync_45_ts=14, sync_45_ts=14)",0.0
1048,1955,12.0,0.18,401,1,3,"(sync_46_ts=0, sync_46_ts=0)",0.0
1049,1955,12.0,0.18,401,2,3,"(sync_48_ts=1, sync_48_ts=1)",0.0
1050,1955,12.0,0.18,401,3,3,"(sync_47_ts=2, sync_47_ts=2)",0.0
1051,1955,12.0,0.18,401,4,3,"(sync_49_ts=3, sync_49_ts=3)",0.0
1052,1955,12.0,0.18,401,5,3,"(sync_50_ts=4, sync_50_ts=4)",0.0
1053,1955,12.0,0.18,401,6,3,"(sync_51_ts=5, sync_51_ts=5)",0.0
1054,1955,12.0,0.18,401,7,3,"(sync_17_ts=6, sync_17_ts=6)",0.0
1055,1955,12.0,0.18,401,8,3,"(sync_18_ts=7, sync_18_ts=7)",0.0
1056,1955,12.0,0.18,401,9,3,"(sync_19_ts=8, sync_19_ts=8)",0.0
1057,1955,12.0,0.18,401,10,3,"(sync_21_ts=9, sync_21_ts=9)",0.0
1058,1955,12.0,0.18,401,11,3,"(sync_23_ts=10, sync_23_ts=10)",0.0
1059,1955,12.0,0.18,401,12,3,"(20_ts=11, >>)",1
1060,1955,12.0,0.18,401,13,3,"(sync_22_ts=12, sync_22_ts=12)",0.0
1061,1955,12.0,0.18,401,14,3,"(24_ts=13, >>)",1
1062,1955,12.0,0.18,401,15,3,"(sync_25_ts=14, sync_25_ts=14)",0.0
1063,1955,12.0,0.18,401,1,4,"(>>, 20)",1
1064,1955,12.0,0.18,401,2,4,"(>>, 24)",1
1065,1955,12.0,0.18,401,3,4,"(sync_26_ts=0, sync_26_ts=0)",0.0
1066,1955,12.0,0.18,401,4,4,"(sync_1_ts=1, sync_1_ts=1)",0.0
1067,1955,12.0,0.18,401,5,4,"(sync_28_ts=2, sync_28_ts=2)",0.0
1068,1955,12.0,0.18,401,6,4,"(sync_29_ts=3, sync_29_ts=3)",0.0
1069,1955,12.0,0.18,401,7,4,"(sync_33_ts=4, sync_33_ts=4)",0.0
1070,1955,12.0,0.18,401,8,4,"(sync_30_ts=5, sync_30_ts=5)",0.0
1071,1955,12.0,0.18,401,9,4,"(sync_31_ts=6, sync_31_ts=6)",0.0
1072,1955,12.0,0.18,401,10,4,"(sync_34_ts=7, sync_34_ts=7)",0.0
1073,1955,12.0,0.18,401,11,4,"(sync_38_ts=8, sync_38_ts=8)",0.0
1074,1955,12.0,0.18,401,12,4,"(sync_39_ts=9, sync_39_ts=9)",0.0
1075,1955,12.0,0.18,401,13,4,"(sync_36_ts=10, sync_36_ts=10)",0.0
1076,1955,12.0,0.18,401,14,4,"(sync_34_ts=11, sync_34_ts=11)",0.0
1077,1955,12.0,0.18,401,15,4,"(sync_32_ts=12, sync_32_ts=12)",0.0
1078,1955,12.0,0.18,401,16,4,"(sync_38_ts=13, sync_38_ts=13)",0.0
1079,1955,12.0,0.18,401,17,4,"(sync_35_ts=14, sync_35_ts=14)",0.0
1080,1955,12.0,0.18,401,1,5,"(sync_40_ts=0, sync_40_ts=0)",0.0
1081,1955,12.0,0.18,401,2,5,"(sync_41_ts=1, sync_41_ts=1)",0.0
1082,1955,12.0,0.18,401,3,5,"(sync_37_ts=2, sync_37_ts=2)",0.0
1083,1955,12.0,0.18,401,4,5,"(sync_42_ts=3, sync_42_ts=3)",0.0
1084,1955,12.0,0.18,401,5,5,"(sync_17_ts=4, sync_17_ts=4)",0.0
1085,1955,12.0,0.18,401,6,5,"(sync_18_ts=5, sync_18_ts=5)",0.0
1086,1955,12.0,0.18,401,7,5,"(sync_19_ts=6, sync_19_ts=6)",0.0
1087,1955,12.0,0.18,401,8,5,"(20_ts=7, >>)",1
1088,1955,12.0,0.18,401,9,5,"(sync_21_ts=8, sync_21_ts=8)",0.0
1089,1955,12.0,0.18,401,10,5,"(24_ts=9, >>)",1
1090,1955,12.0,0.18,401,11,5,"(sync_23_ts=10, sync_23_ts=10)",0.0
1091,1955,12.0,0.18,401,12,5,"(sync_22_ts=11, sync_22_ts=11)",0.0
1092,1955,12.0,0.18,401,13,5,"(sync_25_ts=12, sync_25_ts=12)",0.0
1093,1955,12.0,0.18,401,14,5,"(26_ts=13, >>)",1
1094,1955,12.0,0.18,401,15,5,"(1_ts=14, >>)",1
1095,1955,12.0,0.18,401,1,6,"(>>, 20)",1
1096,1955,12.0,0.18,401,2,6,"(>>, 24)",1
1097,1955,12.0,0.18,401,3,6,"(>>, 26)",1
1098,1955,12.0,0.18,401,4,6,"(>>, 1)",1
1099,1955,12.0,0.18,401,5,6,"(sync_2_ts=0, sync_2_ts=0)",0.0
1100,1955,12.0,0.18,401,6,6,"(sync_4_ts=1, sync_4_ts=1)",0.0
1101,1955,12.0,0.18,401,7,6,"(sync_8_ts=2, sync_8_ts=2)",0.0
1102,1955,12.0,0.18,401,8,6,"(sync_10_ts=3, sync_10_ts=3)",0.0
1103,1955,12.0,0.18,401,9,6,"(sync_3_ts=4, sync_3_ts=4)",0.0
1104,1955,12.0,0.18,401,10,6,"(sync_9_ts=5, sync_9_ts=5)",0.0
1105,1955,12.0,0.18,401,11,6,"(sync_5_ts=6, sync_5_ts=6)",0.0
1106,1955,12.0,0.18,401,12,6,"(sync_6_ts=7, sync_6_ts=7)",0.0
1107,1955,12.0,0.18,401,13,6,"(sync_11_ts=8, sync_11_ts=8)",0.0
1108,1955,12.0,0.18,401,14,6,"(sync_12_ts=9, sync_12_ts=9)",0.0
1109,1955,12.0,0.18,401,15,6,"(sync_14_ts=10, sync_14_ts=10)",0.0
1110,1955,12.0,0.18,401,16,6,"(sync_13_ts=11, sync_13_ts=11)",0.0
1111,1955,12.0,0.18,401,17,6,"(sync_3_ts=12, sync_3_ts=12)",0.0
1112,1955,12.0,0.18,401,18,6,"(sync_11_ts=13, sync_11_ts=13)",0.0
1113,1955,12.0,0.18,401,19,6,"(sync_13_ts=14, sync_13_ts=14)",0.0
1114,1955,12.0,0.18,401,1,7,"(sync_3_ts=0, sync_3_ts=0)",0.0
1115,1955,12.0,0.18,401,2,7,"(sync_7_ts=1, sync_7_ts=1)",0.0
1116,1955,12.0,0.18,401,3,7,"(sync_11_ts=2, sync_11_ts=2)",0.0
1117,1955,12.0,0.18,401,4,7,"(sync_13_ts=3, sync_13_ts=3)",0.0
1118,1955,12.0,0.18,401,5,7,"(sync_3_ts=4, sync_3_ts=4)",0.0
1119,1955,12.0,0.18,401,6,7,"(sync_11_ts=5, sync_11_ts=5)",0.0
1120,1955,12.0,0.18,401,7,7,"(sync_15_ts=6, sync_15_ts=6)",0.0
1121,1955,12.0,0.18,401,8,7,"(sync_16_ts=7, sync_16_ts=7)",0.0
1122,1955,12.0,0.18,401,9,7,"(sync_17_ts=8, sync_17_ts=8)",0.0
1123,1955,12.0,0.18,401,10,7,"(sync_43_ts=9, sync_43_ts=9)",0.0